import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme/theme-provider"
import Header from "@/components/dashboard/header/header"
import MainNav from "@/components/dashboard/main-nav/main-nav"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="h-screen flex flex-col px-4 md:px-8 ">
              <Header />
              <div className="my-4 py-4">
                <MainNav />
              </div>
              <div className="flex-1 rounded-xl bg-muted/20 p-4">
                {children}
              </div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
